name: app_screen_privacy
description: "Privacy screen plugin for Flutter apps to prevent screenshots and screen recordings."
version: 0.0.1
homepage: https://github.com/naninydhruva/app_screen_privacy
repository: https://github.com/naninydhruva/app_screen_privacy
issue_tracker: https://github.com/naninydhruva/app_screen_privacy/issues
environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.csndhruva.app_screen_privacy
        pluginClass: AppScreenPrivacyPlugin
      ios:
        pluginClass: AppScreenPrivacyPlugin
